### ISSUE TITLE
Abort on error

### ISSUE THREAD

**Issue by Guite** [LinuxSuRen/hugo-plugin#3]
It would be great if this plugin could cause the build to fail if Hugo output contains (or ends with) `FATAL: Hugo build error, exit code: 255`.

**Comment by Guite** [comment]
Not nice but possible workaround:
```
            //hugo([
            //    verbose: true
            //])
            def out = sh script: 'hugo --destination .public --verbose', returnStdout: true
            echo 'Checking console output for any errors...'
            if (out.contains('FATAL: Hugo build error, exit code: 255')) {
                throw new Exception()
            }
```

**Comment by LinuxSuRen** [comment]
@Guite Thanks for your response. I'll try to fix this as soon as possible. Or if you are interested to create a PR.
